version: "3"
services: 
  node_backend:
    container_name: "node_backend"
    build: 
      context: .
    volumes:
      - ./:/usr/src/app
    # depends_on:
      # - "db"
    command: nodemon ./bin/www
    ports: 
      - "3000:3000"
  # db:
  #   image: postgres
  #   environment: 
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports: 
  #     - "55432:5432"
